name: lutris-mts
version: git
confinement: strict
base: core18
grade: stable

architectures:
  - build-on: [amd64]
    run-on: [amd64]

summary: lutris snap
description: |
  Lutris is a gaming platform for GNU/Linux. Its goal is to make
  gaming on Linux as easy as possible by taking care of installing
  and setting up the game for the user. The only thing you have to
  do is play the game. It aims to support every game that is playable
  on Linux.

parts:

  lutis:
    plugin: python
    python-version: python3
    source: https://github.com/lutris/lutris.git
    build-packages: [python3-all-dev, python3-cairo-dev, libgirepository1.0-dev]
    stage-packages: [python3-all-dev, python3-cairo-dev, libgirepository1.0-dev,python3-pip, python3-cairo, python3-yaml, python3-requests, python3-pil, python3-gi, gir1.2-gtk-3.0, gir1.2-gnomedesktop-3.0, gir1.2-webkit2-4.0, gir1.2-notify-0.7, curl, libc6-i386, lib32gcc1]
    override-build: |
      snapcraftctl build
      sed -i 's|Name=Lutris|Name=Lutris-MTS|' ${SNAPCRAFT_PART_INSTALL}/share/applications/net.lutris.Lutris.desktop
    after: [desktop-gnome-platform, wine]

  wine:
    plugin: make
    source: git://source.winehq.org/git/wine.git
    build-packages: [gcc-multilib, g++-multilib]
    stage-packages: [gcc-multilib, g++-multilib] #is it needed?? try...
    override-build: |
      $SNAPCRAFT_PART_SRC/configure --enable-win64 --without-freetype
      snapcraftctl build

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: gtk
    plugin: make
    build-packages: [build-essential, libgtk-3-dev, flex, bison]
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

plugs:

  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes

  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

slots:

  lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris

apps:

  lutris:
    command: bin/desktop-launch $SNAP/bin/lutris -d
    plugs: [home, daemon-notify, network, network-bind, network-manager, desktop, desktop-legacy, unity7, wayland, opengl, pulseaudio, gsettings, x11, screen-inhibit-control, kvm, libvirt, removable-media, joystick, io-ports-control, dbus, hardware-observe, mount-observe]
    slots: [lutris]
    desktop: share/applications/net.lutris.Lutris.desktop
  
  lutris-wrapper:
    command: bin/desktop-launch bin/lutris-wrapper
  
  wine:
    command: bin/desktop-launch bin/wine